[build]
  publish = "build"
  command = "yarn build"

[[redirects]]
  from = "/api/gnawty.webp"
  to = "/.netlify/functions/gnawty"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions.gnawty]
  included_files = ["netlify/assets/walkin.webp"]